import { query } from '../config/db';
import { Proprietaire } from '../types';

// What the API caller can supply at creation. created_at + reference_prop
// are generated by Postgres.
export interface CreateProprietaireInput {
  nom: string;
  email: string;
  telephone?: string | null;
}

// Update accepts any subset of the fields above.
export interface UpdateProprietaireInput {
  nom?: string;
  email?: string;
  telephone?: string | null;
}

export class ProprietaireModel {
  // List all owners, most recent first. Pagination can be added later.
  static async findAll(): Promise<Proprietaire[]> {
    const sql = `
      SELECT reference_prop, nom, email, telephone, created_at, updated_at
      FROM proprietaires
      ORDER BY nom ASC
    `;
    return query<Proprietaire>(sql);
  }

  // Single owner by id.
  static async findById(id: number): Promise<Proprietaire | null> {
    const sql = `
      SELECT reference_prop, nom, email, telephone, created_at, updated_at
      FROM proprietaires
      WHERE reference_prop = $1
    `;
    const rows = await query<Proprietaire>(sql, [id]);
    return rows[0] ?? null;
  }

  // Lookup by email. Used to reject duplicates BEFORE the INSERT — gives
  // a friendlier 409 error than waiting for the UNIQUE constraint to fire.
  static async findByEmail(email: string): Promise<Proprietaire | null> {
    const sql = `
      SELECT reference_prop, nom, email, telephone, created_at, updated_at
      FROM proprietaires
      WHERE email = $1
    `;
    const rows = await query<Proprietaire>(sql, [email]);
    return rows[0] ?? null;
  }

  // Insert and return the new row.
  static async create(data: CreateProprietaireInput): Promise<Proprietaire> {
    const sql = `
      INSERT INTO proprietaires (nom, email, telephone)
      VALUES ($1, $2, $3)
      RETURNING reference_prop, nom, email, telephone, created_at, updated_at
    `;
    // telephone is optional; coerce undefined to null so pg stores NULL.
    const rows = await query<Proprietaire>(sql, [
      data.nom,
      data.email,
      data.telephone ?? null,
    ]);
    return rows[0];
  }

  // Partial update — same dynamic SET pattern as UserModel.
  static async update(
    id: number,
    data: UpdateProprietaireInput
  ): Promise<Proprietaire | null> {
    const entries = Object.entries(data).filter(([, v]) => v !== undefined);
    if (entries.length === 0) return this.findById(id);

    const setClause = entries.map(([k], i) => `${k} = $${i + 1}`).join(', ');
    const values = entries.map(([, v]) => v);

    const sql = `
      UPDATE proprietaires
      SET ${setClause}
      WHERE reference_prop = $${entries.length + 1}
      RETURNING reference_prop, nom, email, telephone, created_at, updated_at
    `;
    const rows = await query<Proprietaire>(sql, [...values, id]);
    return rows[0] ?? null;
  }

  // Hard delete — owners are not soft-deleted. Cascading FK on patients
  // means deleting an owner removes their pets (matches cahier semantics).
  static async remove(id: number): Promise<boolean> {
    const sql = 'DELETE FROM proprietaires WHERE reference_prop = $1';
    await query(sql, [id]);
    return true;
  }

  // ------------------------------------------------------------------------
  // findAnimals — owner's pets. JOIN here keeps logic on the DB side, which
  // is faster than two round-trips. Order matches the dashboard mockup.
  // ------------------------------------------------------------------------
  static async findAnimals(ownerId: number) {
    const sql = `
      SELECT reference_patient, nom, espece, actif
      FROM patients
      WHERE proprietaire_id = $1
      ORDER BY nom ASC
    `;
    return query(sql, [ownerId]);
  }
}