// We import our query helper (parametrized, safe) and the User type contract.
import { query } from '../config/db';
import { User, UserRole } from '../types';

// Input shape for creating a user. created_at, is_active, reference_user are
// generated by the DB — the API caller must not supply them.
export interface CreateUserInput {
  email: string;
  password_hash: string;        // already hashed by the controller
  role: UserRole;
}

// Input shape for updating. Every field is optional — partial updates allowed.
export interface UpdateUserInput {
  email?: string;
  password_hash?: string;
  role?: UserRole;
  is_active?: boolean;
}

// Static methods are organized inside a class because we like grouping by
// entity. Plain object would also work; the choice is style + auto-imports.

export class UserModel {
  // ------------------------------------------------------------------------
  // findAll — list every user. Used by admin staff management.
  // We never expose password_hash through the API but the model returns it
  // because login needs it. The controller decides what to send to clients.
  // ------------------------------------------------------------------------
  static async findAll(): Promise<User[]> {
    const sql = `
      SELECT reference_user, email, password_hash, role, is_active,
             created_at, updated_at
      FROM users
      ORDER BY created_at DESC
    `;
    return query<User>(sql);
  }

  // ------------------------------------------------------------------------
  // findById — fetch one user. Returns null if not found.
  // We use null (not undefined) because rows are absent vs. unknown is
  // a different concept — null represents "looked, didn't exist".
  // ------------------------------------------------------------------------
  static async findById(id: number): Promise<User | null> {
    const sql = `
      SELECT reference_user, email, password_hash, role, is_active,
             created_at, updated_at
      FROM users
      WHERE reference_user = $1
    `;
    const rows = await query<User>(sql, [id]);
    return rows[0] ?? null;
  }

  // ------------------------------------------------------------------------
  // findByEmail — used by login. Email is unique so we expect 0 or 1 row.
  // ------------------------------------------------------------------------
  static async findByEmail(email: string): Promise<User | null> {
    const sql = `
      SELECT reference_user, email, password_hash, role, is_active,
             created_at, updated_at
      FROM users
      WHERE email = $1
    `;
    const rows = await query<User>(sql, [email]);
    return rows[0] ?? null;
  }

  // ------------------------------------------------------------------------
  // create — insert and return the new row.
  // RETURNING * gives us the generated reference_user + timestamps in one
  // round-trip (no second SELECT needed).
  // ------------------------------------------------------------------------
  static async create(data: CreateUserInput): Promise<User> {
    const sql = `
      INSERT INTO users (email, password_hash, role)
      VALUES ($1, $2, $3)
      RETURNING reference_user, email, password_hash, role, is_active,
                created_at, updated_at
    `;
    const rows = await query<User>(sql, [data.email, data.password_hash, data.role]);
    return rows[0];
  }

  // ------------------------------------------------------------------------
  // update — partial update. Only the fields present in `data` are changed.
  // We build the SET clause dynamically so we never overwrite a column with
  // null when the caller didn't intend to touch it.
  // ------------------------------------------------------------------------
  static async update(id: number, data: UpdateUserInput): Promise<User | null> {
    // Collect only defined fields. Using Object.entries keeps types in sync.
    const entries = Object.entries(data).filter(([, v]) => v !== undefined);

    // Nothing to update — return the current row instead of running a no-op query.
    if (entries.length === 0) return this.findById(id);

    // Build "field = $1, field = $2, ..." dynamically.
    // Keys are hard-coded keyof UpdateUserInput — safe from injection.
    const setClause = entries.map(([k], i) => `${k} = $${i + 1}`).join(', ');
    const values = entries.map(([, v]) => v);

    // The id parameter goes last; its placeholder is one past the others.
    const sql = `
      UPDATE users
      SET ${setClause}
      WHERE reference_user = $${entries.length + 1}
      RETURNING reference_user, email, password_hash, role, is_active,
                created_at, updated_at
    `;
    const rows = await query<User>(sql, [...values, id]);
    return rows[0] ?? null;
  }

  // ------------------------------------------------------------------------
  // remove — hard delete. Generally we soft-delete (is_active=false), but
  // this method is kept for admin tooling / tests / data cleanup.
  // ------------------------------------------------------------------------
  static async remove(id: number): Promise<boolean> {
    const sql = 'DELETE FROM users WHERE reference_user = $1';
    const result = await query(sql, [id]);
    // pg returns rowCount on the result; our helper returns rows only.
    // For DELETE/UPDATE, an empty array means 0 rows touched — same outcome.
    // We expose a boolean for ergonomics.
    return Array.isArray(result);
  }

  // ------------------------------------------------------------------------
  // setActive — toggle is_active flag. Used to disable an account without
  // losing audit trail (US-03 admin requirement).
  // ------------------------------------------------------------------------
  static async setActive(id: number, active: boolean): Promise<User | null> {
    const sql = `
      UPDATE users
      SET is_active = $1
      WHERE reference_user = $2
      RETURNING reference_user, email, password_hash, role, is_active,
                created_at, updated_at
    `;
    const rows = await query<User>(sql, [active, id]);
    return rows[0] ?? null;
  }
}