-- ============================================================================
-- Seed data for VetCare demo
-- Run AFTER schema.sql.
-- ============================================================================

-- Clear in dependency-safe order so seed can be re-run.
TRUNCATE TABLE patients_traitements RESTART IDENTITY CASCADE;
TRUNCATE TABLE dossier_traitements  RESTART IDENTITY CASCADE;
TRUNCATE TABLE traitements          RESTART IDENTITY CASCADE;
TRUNCATE TABLE consultations        RESTART IDENTITY CASCADE;
TRUNCATE TABLE dossier              RESTART IDENTITY CASCADE;
TRUNCATE TABLE patients             RESTART IDENTITY CASCADE;
TRUNCATE TABLE proprietaires        RESTART IDENTITY CASCADE;
TRUNCATE TABLE users                RESTART IDENTITY CASCADE;

-- ----------------------------------------------------------------------------
-- Users
-- All passwords are pre-hashed with Argon2id. Plaintext for demo is below:
--   admin@vetcare.fr      → "Admin1234!"
--   marie@vetcare.fr      → "Vet1234!"
--   sofia@vetcare.fr      → "Asst1234!"
-- The hashes were generated by running:
--   node -e "require('argon2').hash('Admin1234!').then(console.log)"
-- ----------------------------------------------------------------------------
INSERT INTO users (email, password_hash, role) VALUES
  ('admin@vetcare.fr',
   '$argon2id$v=19$m=65536,t=3,p=4$placeholderhashreplaceonseed01$placeholdersigreplaceonseed02',
   'administrateur'),
  ('marie@vetcare.fr',
   '$argon2id$v=19$m=65536,t=3,p=4$placeholderhashreplaceonseed03$placeholdersigreplaceonseed04',
   'veterinaire'),
  ('sofia@vetcare.fr',
   '$argon2id$v=19$m=65536,t=3,p=4$placeholderhashreplaceonseed05$placeholdersigreplaceonseed06',
   'assistant');

-- ----------------------------------------------------------------------------
-- Proprietaires
-- ----------------------------------------------------------------------------
INSERT INTO proprietaires (nom, email, telephone) VALUES
  ('Jean Dupont',     'jean.dupont@email.fr',    '+33 6 12 34 56 78'),
  ('Camille Martin',  'camille.martin@email.fr', '+33 6 98 76 54 32'),
  ('Pierre Bernard',  'pierre.bernard@email.fr', '+33 6 11 22 33 44');

-- ----------------------------------------------------------------------------
-- Patients
-- ----------------------------------------------------------------------------
INSERT INTO patients (nom, espece, veterinaire, actif, proprietaire_id) VALUES
  ('Milo',     'chien',   'Dr. Marie Lambert', TRUE, 1),
  ('Luna',     'chat',    'Dr. Marie Lambert', TRUE, 2),
  ('Coco',     'oiseau',  'Dr. Marie Lambert', TRUE, 3),
  ('Hercule',  'lapin',   'Dr. Marie Lambert', TRUE, 1);

-- ----------------------------------------------------------------------------
-- Dossier — one row per patient, created automatically in real flow.
-- We seed manually here for the demo.
-- ----------------------------------------------------------------------------
INSERT INTO dossier (patient_id, allergie, intolerance, condition_physique) VALUES
  (1, 'Aucune connue',           NULL,           'Très bon état général'),
  (2, 'Pollen au printemps',     'Lactose',      'Stérilisée, vaccins à jour'),
  (3, NULL,                      NULL,           'Léger surpoids'),
  (4, NULL,                      'Foin moisi',   'Bonne santé');

-- ----------------------------------------------------------------------------
-- Consultations
-- ----------------------------------------------------------------------------
INSERT INTO consultations (patient_id, veterinaire_id, date, status, motif) VALUES
  (1, 2, NOW() - INTERVAL '7 days',  'terminee', 'Vaccination annuelle'),
  (2, 2, NOW() - INTERVAL '3 days',  'terminee', 'Contrôle post-stérilisation'),
  (3, 2, NOW() + INTERVAL '2 days',  'prevue',   'Première visite'),
  (1, 2, NOW() + INTERVAL '14 days', 'prevue',   'Rappel vaccin');

-- ----------------------------------------------------------------------------
-- Traitements
-- ----------------------------------------------------------------------------
INSERT INTO traitements (medicament, status) VALUES
  ('Frontline Combo',     'en_cours'),
  ('Antibiotique Doxy',   'termine'),
  ('Vermifuge Milbemax',  'en_cours');

-- Junction: link traitements to dossiers.
INSERT INTO dossier_traitements (dossier_id, traitement_id) VALUES
  (1, 1), (2, 1), (2, 2), (3, 3);

-- Junction: link traitements to patients (with start dates).
INSERT INTO patients_traitements (patient_id, traitement_id, date_debut) VALUES
  (1, 1, CURRENT_DATE - INTERVAL '30 days'),
  (2, 1, CURRENT_DATE - INTERVAL '45 days'),
  (2, 2, CURRENT_DATE - INTERVAL '60 days'),
  (3, 3, CURRENT_DATE - INTERVAL '10 days');